nginx:
  enabled: true
  chart: "bitnami/nginx"
  service:
    type: ClusterIP
  podSecurityContext:
    enabled: false
  containerSecurityContext:
    enabled: false
  networkPolicy:
    enabled: false
  ingress:
    enabled: true
    annotations:
      aviinfrasetting.ako.vmware.com/name: "dataclass-medium"
    hostname: nginx-{{cookiecutter.licence_plate}}-prod.apps.emerald.devops.gov.bc.ca
  version: "{{ cookiecutter.nginx_version }}"
  image:
    pullPolicy: Always
  podLabels:
    environment: prod
    env: production
    owner: "{{cookiecutter.team_name}}"
    project: "{{cookiecutter.project_name}}"
    DataClass: "Medium"
  commonLabels:
    environment: prod
    env: production
    owner: "{{cookiecutter.team_name}}"
    project: "{{cookiecutter.project_name}}"
    DataClass: "Medium"
  replicaCount: 2

postgresql:
  enabled: true
  image:
    pullPolicy: Always
  commonLabels:
    environment: prod
    env: production
    owner: "{{cookiecutter.team_name}}"
    project: "{{cookiecutter.project_name}}"
    DataClass: "Medium"
  primary:
    podSecurityContext:
      enabled: false
    containerSecurityContext:
      enabled: false
    networkPolicy:
      enabled: false
    labels:
      environment: prod
      env: production
      owner: "{{cookiecutter.team_name}}"
      project: "{{cookiecutter.project_name}}"
      DataClass: "Medium"
    podLabels:
      environment: prod
      env: production
      owner: "{{cookiecutter.team_name}}"
      project: "{{cookiecutter.project_name}}"
      DataClass: "Medium"
    resources:
      limits:
        cpu: 200m
        memory: 1Gi
      requests:
        memory: 256Mi
        cpu: 100m
  replicaCount: 2
